In [4]:
#Numpy Assignment
#1.Create a null vector of size 10 but the fifth value which is 1
import numpy as np
x = np.zeros(10)
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [5]:
#2.Create a vector with values ranging from 10 to 49

v= np.arange(10,49)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [10]:
#3.Create a 3x3 matrix with values ranging from 0 to 8
mat2 = np.arange(9).reshape(3,3)
print ('3x3 matrix generated with values ranging from 0 to 8 \n%s\n'%mat2)

3x3 matrix generated with values ranging from 0 to 8 
[[0 1 2]
 [3 4 5]
 [6 7 8]]



In [23]:
#4.Find indices of non-zero elements from [1,2,0,0,4,0]
a = np.nonzero([1,2,0,0,4,0])
print('Indices of non-zero element \n%s'%a)



Indices of non-zero element 
[0 1 4]


In [24]:
#5.Create a 10x10 array with random values and find the minimum and maximum values
l = np.random.random((10,10))
#print(l)
lmin = l.min()
lmax = l.max()
print('The Minimum Values:\n%s'%lmin)
print('The Maximum Values:\n%s'%lmax)



The Minimum Values:
0.008723841191228598
The Maximum Values:
0.9965121783660886


In [28]:
#6. Create a random vector of size 30 and find the mean value.
z = np.random.random(30)
d = z.mean()
print('The Mean value:\n%s'%d)


The Mean value:
0.5502175247684682
